// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jsj.rpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   *name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
