// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jsj.rpc;

public final class User {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_UserInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_UserInfo_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_UserDetail_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_UserDetail_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\nuser.proto\032\031google/protobuf/any.proto\"" +
                        "1\n\010UserInfo\022\n\n\002id\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\022\013\n" +
                        "\003age\030\003 \001(\r\";\n\nUserDetail\022\033\n\010userInfo\030\001 \001" +
                        "(\0132\t.UserInfo\022\020\n\010password\030\003 \001(\tB\023\n\013com.j" +
                        "sj.rpcB\004Userb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                        }, assigner);
        internal_static_UserInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_UserInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_UserInfo_descriptor,
                new String[]{"Id", "Name", "Age",});
        internal_static_UserDetail_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_UserDetail_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_UserDetail_descriptor,
                new String[]{"UserInfo", "Password",});
        com.google.protobuf.AnyProto.getDescriptor();
    }

    private User() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface UserInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:UserInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * id
         * </pre>
         *
         * <code>uint64 id = 1;</code>
         */
        long getId();

        /**
         * <pre>
         * name
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        String getName();

        /**
         * <pre>
         * name
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <pre>
         * age
         * </pre>
         *
         * <code>uint32 age = 3;</code>
         */
        int getAge();
    }

    public interface UserDetailOrBuilder extends
            // @@protoc_insertion_point(interface_extends:UserDetail)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * user info
         * </pre>
         *
         * <code>.UserInfo userInfo = 1;</code>
         */
        boolean hasUserInfo();

        /**
         * <pre>
         * user info
         * </pre>
         *
         * <code>.UserInfo userInfo = 1;</code>
         */
        UserInfo getUserInfo();

        /**
         * <pre>
         * user info
         * </pre>
         *
         * <code>.UserInfo userInfo = 1;</code>
         */
        UserInfoOrBuilder getUserInfoOrBuilder();

        /**
         * <pre>
         * password
         * </pre>
         *
         * <code>string password = 3;</code>
         */
        String getPassword();

        /**
         * <pre>
         * password
         * </pre>
         *
         * <code>string password = 3;</code>
         */
        com.google.protobuf.ByteString
        getPasswordBytes();
    }

    /**
     * Protobuf type {@code UserInfo}
     */
    public static final class UserInfo extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:UserInfo)
            UserInfoOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        public static final int NAME_FIELD_NUMBER = 2;
        public static final int AGE_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:UserInfo)
        private static final UserInfo DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<UserInfo>
                PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
            public UserInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UserInfo(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new UserInfo();
        }

        private long id_;
        private volatile Object name_;
        private int age_;
        private byte memoizedIsInitialized = -1;

        // Use UserInfo.newBuilder() to construct.
        private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private UserInfo() {
            id_ = 0L;
            name_ = "";
            age_ = 0;
        }

        private UserInfo(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 24: {

                            age_ = input.readUInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return User.internal_static_UserInfo_descriptor;
        }

        public static UserInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static UserInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(UserInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static UserInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<UserInfo> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return User.internal_static_UserInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UserInfo.class, Builder.class);
        }

        /**
         * <pre>
         * id
         * </pre>
         *
         * <code>uint64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        /**
         * <pre>
         * name
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * name
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * age
         * </pre>
         *
         * <code>uint32 age = 3;</code>
         */
        public int getAge() {
            return age_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (age_ != 0) {
                output.writeUInt32(3, age_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, age_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof UserInfo)) {
                return super.equals(obj);
            }
            UserInfo other = (UserInfo) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getName()
                    .equals(other.getName());
            result = result && (getAge()
                    == other.getAge());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<UserInfo> getParserForType() {
            return PARSER;
        }

        public UserInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code UserInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:UserInfo)
                UserInfoOrBuilder {
            private long id_;
            private Object name_ = "";
            private int age_;

            // Construct using com.jsj.rpc.User.UserInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return User.internal_static_UserInfo_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return User.internal_static_UserInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UserInfo.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                name_ = "";

                age_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return User.internal_static_UserInfo_descriptor;
            }

            public UserInfo getDefaultInstanceForType() {
                return UserInfo.getDefaultInstance();
            }

            public UserInfo build() {
                UserInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public UserInfo buildPartial() {
                UserInfo result = new UserInfo(this);
                result.id_ = id_;
                result.name_ = name_;
                result.age_ = age_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof UserInfo) {
                    return mergeFrom((UserInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(UserInfo other) {
                if (other == UserInfo.getDefaultInstance()) return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                UserInfo parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (UserInfo) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <pre>
             * id
             * </pre>
             *
             * <code>uint64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <pre>
             * id
             * </pre>
             *
             * <code>uint64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * id
             * </pre>
             *
             * <code>uint64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * name
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * name
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * name
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * name
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * name
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * age
             * </pre>
             *
             * <code>uint32 age = 3;</code>
             */
            public int getAge() {
                return age_;
            }

            /**
             * <pre>
             * age
             * </pre>
             *
             * <code>uint32 age = 3;</code>
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * age
             * </pre>
             *
             * <code>uint32 age = 3;</code>
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:UserInfo)
        }

    }

    /**
     * Protobuf type {@code UserDetail}
     */
    public static final class UserDetail extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:UserDetail)
            UserDetailOrBuilder {
        public static final int USERINFO_FIELD_NUMBER = 1;
        public static final int PASSWORD_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:UserDetail)
        private static final UserDetail DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<UserDetail>
                PARSER = new com.google.protobuf.AbstractParser<UserDetail>() {
            public UserDetail parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UserDetail(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new UserDetail();
        }

        private UserInfo userInfo_;
        private volatile Object password_;
        private byte memoizedIsInitialized = -1;

        // Use UserDetail.newBuilder() to construct.
        private UserDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private UserDetail() {
            password_ = "";
        }

        private UserDetail(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            UserInfo.Builder subBuilder = null;
                            if (userInfo_ != null) {
                                subBuilder = userInfo_.toBuilder();
                            }
                            userInfo_ = input.readMessage(UserInfo.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(userInfo_);
                                userInfo_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            password_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return User.internal_static_UserDetail_descriptor;
        }

        public static UserDetail parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserDetail parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserDetail parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserDetail parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserDetail parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserDetail parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserDetail parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserDetail parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserDetail parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static UserDetail parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserDetail parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserDetail parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(UserDetail prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static UserDetail getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<UserDetail> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return User.internal_static_UserDetail_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UserDetail.class, Builder.class);
        }

        /**
         * <pre>
         * user info
         * </pre>
         *
         * <code>.UserInfo userInfo = 1;</code>
         */
        public boolean hasUserInfo() {
            return userInfo_ != null;
        }

        /**
         * <pre>
         * user info
         * </pre>
         *
         * <code>.UserInfo userInfo = 1;</code>
         */
        public UserInfo getUserInfo() {
            return userInfo_ == null ? UserInfo.getDefaultInstance() : userInfo_;
        }

        /**
         * <pre>
         * user info
         * </pre>
         *
         * <code>.UserInfo userInfo = 1;</code>
         */
        public UserInfoOrBuilder getUserInfoOrBuilder() {
            return getUserInfo();
        }

        /**
         * <pre>
         * password
         * </pre>
         *
         * <code>string password = 3;</code>
         */
        public String getPassword() {
            Object ref = password_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                password_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * password
         * </pre>
         *
         * <code>string password = 3;</code>
         */
        public com.google.protobuf.ByteString
        getPasswordBytes() {
            Object ref = password_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (userInfo_ != null) {
                output.writeMessage(1, getUserInfo());
            }
            if (!getPasswordBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (userInfo_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getUserInfo());
            }
            if (!getPasswordBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof UserDetail)) {
                return super.equals(obj);
            }
            UserDetail other = (UserDetail) obj;

            boolean result = true;
            result = result && (hasUserInfo() == other.hasUserInfo());
            if (hasUserInfo()) {
                result = result && getUserInfo()
                        .equals(other.getUserInfo());
            }
            result = result && getPassword()
                    .equals(other.getPassword());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUserInfo()) {
                hash = (37 * hash) + USERINFO_FIELD_NUMBER;
                hash = (53 * hash) + getUserInfo().hashCode();
            }
            hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
            hash = (53 * hash) + getPassword().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<UserDetail> getParserForType() {
            return PARSER;
        }

        public UserDetail getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code UserDetail}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:UserDetail)
                UserDetailOrBuilder {
            private UserInfo userInfo_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    UserInfo, UserInfo.Builder, UserInfoOrBuilder> userInfoBuilder_;
            private Object password_ = "";

            // Construct using com.jsj.rpc.User.UserDetail.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return User.internal_static_UserDetail_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return User.internal_static_UserDetail_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UserDetail.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (userInfoBuilder_ == null) {
                    userInfo_ = null;
                } else {
                    userInfo_ = null;
                    userInfoBuilder_ = null;
                }
                password_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return User.internal_static_UserDetail_descriptor;
            }

            public UserDetail getDefaultInstanceForType() {
                return UserDetail.getDefaultInstance();
            }

            public UserDetail build() {
                UserDetail result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public UserDetail buildPartial() {
                UserDetail result = new UserDetail(this);
                if (userInfoBuilder_ == null) {
                    result.userInfo_ = userInfo_;
                } else {
                    result.userInfo_ = userInfoBuilder_.build();
                }
                result.password_ = password_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof UserDetail) {
                    return mergeFrom((UserDetail) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(UserDetail other) {
                if (other == UserDetail.getDefaultInstance()) return this;
                if (other.hasUserInfo()) {
                    mergeUserInfo(other.getUserInfo());
                }
                if (!other.getPassword().isEmpty()) {
                    password_ = other.password_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                UserDetail parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (UserDetail) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public boolean hasUserInfo() {
                return userInfoBuilder_ != null || userInfo_ != null;
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public UserInfo getUserInfo() {
                if (userInfoBuilder_ == null) {
                    return userInfo_ == null ? UserInfo.getDefaultInstance() : userInfo_;
                } else {
                    return userInfoBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public Builder setUserInfo(UserInfo value) {
                if (userInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    userInfo_ = value;
                    onChanged();
                } else {
                    userInfoBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public Builder setUserInfo(
                    UserInfo.Builder builderForValue) {
                if (userInfoBuilder_ == null) {
                    userInfo_ = builderForValue.build();
                    onChanged();
                } else {
                    userInfoBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public Builder mergeUserInfo(UserInfo value) {
                if (userInfoBuilder_ == null) {
                    if (userInfo_ != null) {
                        userInfo_ =
                                UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
                    } else {
                        userInfo_ = value;
                    }
                    onChanged();
                } else {
                    userInfoBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public Builder clearUserInfo() {
                if (userInfoBuilder_ == null) {
                    userInfo_ = null;
                    onChanged();
                } else {
                    userInfo_ = null;
                    userInfoBuilder_ = null;
                }

                return this;
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public UserInfo.Builder getUserInfoBuilder() {

                onChanged();
                return getUserInfoFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            public UserInfoOrBuilder getUserInfoOrBuilder() {
                if (userInfoBuilder_ != null) {
                    return userInfoBuilder_.getMessageOrBuilder();
                } else {
                    return userInfo_ == null ?
                            UserInfo.getDefaultInstance() : userInfo_;
                }
            }

            /**
             * <pre>
             * user info
             * </pre>
             *
             * <code>.UserInfo userInfo = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    UserInfo, UserInfo.Builder, UserInfoOrBuilder>
            getUserInfoFieldBuilder() {
                if (userInfoBuilder_ == null) {
                    userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            UserInfo, UserInfo.Builder, UserInfoOrBuilder>(
                            getUserInfo(),
                            getParentForChildren(),
                            isClean());
                    userInfo_ = null;
                }
                return userInfoBuilder_;
            }

            /**
             * <pre>
             * password
             * </pre>
             *
             * <code>string password = 3;</code>
             */
            public String getPassword() {
                Object ref = password_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    password_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * password
             * </pre>
             *
             * <code>string password = 3;</code>
             */
            public Builder setPassword(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * password
             * </pre>
             *
             * <code>string password = 3;</code>
             */
            public com.google.protobuf.ByteString
            getPasswordBytes() {
                Object ref = password_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    password_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * password
             * </pre>
             *
             * <code>string password = 3;</code>
             */
            public Builder setPasswordBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * password
             * </pre>
             *
             * <code>string password = 3;</code>
             */
            public Builder clearPassword() {

                password_ = getDefaultInstance().getPassword();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:UserDetail)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
