// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package com.jsj.rpc.protobuf;

public final class Generic {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_GenericInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_GenericInfo_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\021GenericInfo.proto\032\031google/protobuf/any" +
                        ".proto\"A\n\013GenericInfo\022\013\n\003tag\030\001 \001(\t\022%\n\007de" +
                        "tails\030\002 \003(\0132\024.google.protobuf.AnyB\034\n\021com" +
                        ".jsj.rpc.protoB\007Genericb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                        }, assigner);
        internal_static_GenericInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_GenericInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_GenericInfo_descriptor,
                new String[]{"Tag", "Details",});
        com.google.protobuf.AnyProto.getDescriptor();
    }

    private Generic() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface GenericInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:GenericInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string tag = 1;</code>
         */
        String getTag();

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string tag = 1;</code>
         */
        com.google.protobuf.ByteString
        getTagBytes();

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        java.util.List<com.google.protobuf.Any>
        getDetailsList();

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        com.google.protobuf.Any getDetails(int index);

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        int getDetailsCount();

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        java.util.List<? extends com.google.protobuf.AnyOrBuilder>
        getDetailsOrBuilderList();

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code GenericInfo}
     */
    public static final class GenericInfo extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:GenericInfo)
            GenericInfoOrBuilder {
        public static final int TAG_FIELD_NUMBER = 1;
        public static final int DETAILS_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:GenericInfo)
        private static final GenericInfo DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<GenericInfo>
                PARSER = new com.google.protobuf.AbstractParser<GenericInfo>() {
            public GenericInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new GenericInfo(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new GenericInfo();
        }

        private int bitField0_;
        private volatile Object tag_;
        private java.util.List<com.google.protobuf.Any> details_;
        private byte memoizedIsInitialized = -1;

        // Use GenericInfo.newBuilder() to construct.
        private GenericInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private GenericInfo() {
            tag_ = "";
            details_ = java.util.Collections.emptyList();
        }

        private GenericInfo(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            tag_ = s;
                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                details_ = new java.util.ArrayList<com.google.protobuf.Any>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            details_.add(
                                    input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    details_ = java.util.Collections.unmodifiableList(details_);
                }
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Generic.internal_static_GenericInfo_descriptor;
        }

        public static GenericInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static GenericInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static GenericInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static GenericInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static GenericInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static GenericInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static GenericInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static GenericInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static GenericInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static GenericInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static GenericInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static GenericInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(GenericInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static GenericInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<GenericInfo> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Generic.internal_static_GenericInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            GenericInfo.class, Builder.class);
        }

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string tag = 1;</code>
         */
        public String getTag() {
            Object ref = tag_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                tag_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string tag = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTagBytes() {
            Object ref = tag_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                tag_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        public java.util.List<com.google.protobuf.Any> getDetailsList() {
            return details_;
        }

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        public java.util.List<? extends com.google.protobuf.AnyOrBuilder>
        getDetailsOrBuilderList() {
            return details_;
        }

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        public int getDetailsCount() {
            return details_.size();
        }

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        public com.google.protobuf.Any getDetails(int index) {
            return details_.get(index);
        }

        /**
         * <code>repeated .google.protobuf.Any details = 2;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
                int index) {
            return details_.get(index);
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTagBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tag_);
            }
            for (int i = 0; i < details_.size(); i++) {
                output.writeMessage(2, details_.get(i));
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getTagBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tag_);
            }
            for (int i = 0; i < details_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, details_.get(i));
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof GenericInfo)) {
                return super.equals(obj);
            }
            GenericInfo other = (GenericInfo) obj;

            boolean result = true;
            result = result && getTag()
                    .equals(other.getTag());
            result = result && getDetailsList()
                    .equals(other.getDetailsList());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TAG_FIELD_NUMBER;
            hash = (53 * hash) + getTag().hashCode();
            if (getDetailsCount() > 0) {
                hash = (37 * hash) + DETAILS_FIELD_NUMBER;
                hash = (53 * hash) + getDetailsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<GenericInfo> getParserForType() {
            return PARSER;
        }

        public GenericInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code GenericInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:GenericInfo)
                GenericInfoOrBuilder {
            private int bitField0_;
            private Object tag_ = "";
            private java.util.List<com.google.protobuf.Any> details_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;

            // Construct using com.jsj.rpc.proto.Generic.GenericInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Generic.internal_static_GenericInfo_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Generic.internal_static_GenericInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                GenericInfo.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getDetailsFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                tag_ = "";

                if (detailsBuilder_ == null) {
                    details_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    detailsBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Generic.internal_static_GenericInfo_descriptor;
            }

            public GenericInfo getDefaultInstanceForType() {
                return GenericInfo.getDefaultInstance();
            }

            public GenericInfo build() {
                GenericInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public GenericInfo buildPartial() {
                GenericInfo result = new GenericInfo(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.tag_ = tag_;
                if (detailsBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        details_ = java.util.Collections.unmodifiableList(details_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.details_ = details_;
                } else {
                    result.details_ = detailsBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof GenericInfo) {
                    return mergeFrom((GenericInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(GenericInfo other) {
                if (other == GenericInfo.getDefaultInstance()) return this;
                if (!other.getTag().isEmpty()) {
                    tag_ = other.tag_;
                    onChanged();
                }
                if (detailsBuilder_ == null) {
                    if (!other.details_.isEmpty()) {
                        if (details_.isEmpty()) {
                            details_ = other.details_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureDetailsIsMutable();
                            details_.addAll(other.details_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.details_.isEmpty()) {
                        if (detailsBuilder_.isEmpty()) {
                            detailsBuilder_.dispose();
                            detailsBuilder_ = null;
                            details_ = other.details_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                            detailsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getDetailsFieldBuilder() : null;
                        } else {
                            detailsBuilder_.addAllMessages(other.details_);
                        }
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                GenericInfo parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (GenericInfo) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string tag = 1;</code>
             */
            public String getTag() {
                Object ref = tag_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    tag_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string tag = 1;</code>
             */
            public Builder setTag(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                tag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string tag = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTagBytes() {
                Object ref = tag_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    tag_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string tag = 1;</code>
             */
            public Builder setTagBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                tag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string tag = 1;</code>
             */
            public Builder clearTag() {

                tag_ = getDefaultInstance().getTag();
                onChanged();
                return this;
            }

            private void ensureDetailsIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    details_ = new java.util.ArrayList<com.google.protobuf.Any>(details_);
                    bitField0_ |= 0x00000002;
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public java.util.List<com.google.protobuf.Any> getDetailsList() {
                if (detailsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(details_);
                } else {
                    return detailsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public int getDetailsCount() {
                if (detailsBuilder_ == null) {
                    return details_.size();
                } else {
                    return detailsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.Any getDetails(int index) {
                if (detailsBuilder_ == null) {
                    return details_.get(index);
                } else {
                    return detailsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder setDetails(
                    int index, com.google.protobuf.Any value) {
                if (detailsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDetailsIsMutable();
                    details_.set(index, value);
                    onChanged();
                } else {
                    detailsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder setDetails(
                    int index, com.google.protobuf.Any.Builder builderForValue) {
                if (detailsBuilder_ == null) {
                    ensureDetailsIsMutable();
                    details_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    detailsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder addDetails(com.google.protobuf.Any value) {
                if (detailsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDetailsIsMutable();
                    details_.add(value);
                    onChanged();
                } else {
                    detailsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder addDetails(
                    int index, com.google.protobuf.Any value) {
                if (detailsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDetailsIsMutable();
                    details_.add(index, value);
                    onChanged();
                } else {
                    detailsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder addDetails(
                    com.google.protobuf.Any.Builder builderForValue) {
                if (detailsBuilder_ == null) {
                    ensureDetailsIsMutable();
                    details_.add(builderForValue.build());
                    onChanged();
                } else {
                    detailsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder addDetails(
                    int index, com.google.protobuf.Any.Builder builderForValue) {
                if (detailsBuilder_ == null) {
                    ensureDetailsIsMutable();
                    details_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    detailsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder addAllDetails(
                    Iterable<? extends com.google.protobuf.Any> values) {
                if (detailsBuilder_ == null) {
                    ensureDetailsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, details_);
                    onChanged();
                } else {
                    detailsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder clearDetails() {
                if (detailsBuilder_ == null) {
                    details_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    detailsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public Builder removeDetails(int index) {
                if (detailsBuilder_ == null) {
                    ensureDetailsIsMutable();
                    details_.remove(index);
                    onChanged();
                } else {
                    detailsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.Any.Builder getDetailsBuilder(
                    int index) {
                return getDetailsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
                    int index) {
                if (detailsBuilder_ == null) {
                    return details_.get(index);
                } else {
                    return detailsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public java.util.List<? extends com.google.protobuf.AnyOrBuilder>
            getDetailsOrBuilderList() {
                if (detailsBuilder_ != null) {
                    return detailsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(details_);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.Any.Builder addDetailsBuilder() {
                return getDetailsFieldBuilder().addBuilder(
                        com.google.protobuf.Any.getDefaultInstance());
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.Any.Builder addDetailsBuilder(
                    int index) {
                return getDetailsFieldBuilder().addBuilder(
                        index, com.google.protobuf.Any.getDefaultInstance());
            }

            /**
             * <code>repeated .google.protobuf.Any details = 2;</code>
             */
            public java.util.List<com.google.protobuf.Any.Builder>
            getDetailsBuilderList() {
                return getDetailsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDetailsFieldBuilder() {
                if (detailsBuilder_ == null) {
                    detailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            details_,
                            ((bitField0_ & 0x00000002) == 0x00000002),
                            getParentForChildren(),
                            isClean());
                    details_ = null;
                }
                return detailsBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:GenericInfo)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
