// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInfo.proto

package com.jsj.rpc.protobuf;

public final class User {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_UserInfoProto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_UserInfoProto_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_UserDetailProto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_UserDetailProto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\016UserInfo.proto\"6\n\rUserInfoProto\022\n\n\002id\030" +
                        "\001 \001(\004\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\r\"F\n\017User" +
                        "DetailProto\022 \n\010userInfo\030\001 \001(\0132\016.UserInfo" +
                        "Proto\022\021\n\tpass_word\030\002 \001(\tB\031\n\021com.jsj.rpc." +
                        "protoB\004Userb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_UserInfoProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_UserInfoProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_UserInfoProto_descriptor,
                new String[]{"Id", "Name", "Age",});
        internal_static_UserDetailProto_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_UserDetailProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_UserDetailProto_descriptor,
                new String[]{"UserInfo", "PassWord",});
    }

    private User() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface UserInfoProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:UserInfoProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 id = 1;</code>
         */
        long getId();

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        String getName();

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>uint32 age = 3;</code>
         */
        int getAge();
    }

    public interface UserDetailProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:UserDetailProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.UserInfoProto userInfo = 1;</code>
         */
        boolean hasUserInfo();

        /**
         * <code>.UserInfoProto userInfo = 1;</code>
         */
        UserInfoProto getUserInfo();

        /**
         * <code>.UserInfoProto userInfo = 1;</code>
         */
        UserInfoProtoOrBuilder getUserInfoOrBuilder();

        /**
         * <code>string pass_word = 2;</code>
         */
        String getPassWord();

        /**
         * <code>string pass_word = 2;</code>
         */
        com.google.protobuf.ByteString
        getPassWordBytes();
    }

    /**
     * Protobuf type {@code UserInfoProto}
     */
    public static final class UserInfoProto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:UserInfoProto)
            UserInfoProtoOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        public static final int NAME_FIELD_NUMBER = 2;
        public static final int AGE_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:UserInfoProto)
        private static final UserInfoProto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<UserInfoProto>
                PARSER = new com.google.protobuf.AbstractParser<UserInfoProto>() {
            public UserInfoProto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UserInfoProto(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new UserInfoProto();
        }

        private long id_;
        private volatile Object name_;
        private int age_;
        private byte memoizedIsInitialized = -1;

        // Use UserInfoProto.newBuilder() to construct.
        private UserInfoProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private UserInfoProto() {
            id_ = 0L;
            name_ = "";
            age_ = 0;
        }

        private UserInfoProto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 24: {

                            age_ = input.readUInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return User.internal_static_UserInfoProto_descriptor;
        }

        public static UserInfoProto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserInfoProto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserInfoProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserInfoProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserInfoProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserInfoProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserInfoProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserInfoProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserInfoProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static UserInfoProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserInfoProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserInfoProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(UserInfoProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static UserInfoProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<UserInfoProto> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return User.internal_static_UserInfoProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UserInfoProto.class, Builder.class);
        }

        /**
         * <code>uint64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 指定字段类型为 string，标识号为 1
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>uint32 age = 3;</code>
         */
        public int getAge() {
            return age_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (age_ != 0) {
                output.writeUInt32(3, age_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, age_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof UserInfoProto)) {
                return super.equals(obj);
            }
            UserInfoProto other = (UserInfoProto) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getName()
                    .equals(other.getName());
            result = result && (getAge()
                    == other.getAge());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<UserInfoProto> getParserForType() {
            return PARSER;
        }

        public UserInfoProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code UserInfoProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:UserInfoProto)
                UserInfoProtoOrBuilder {
            private long id_;
            private Object name_ = "";
            private int age_;

            // Construct using com.jsj.rpc.proto.User.UserInfoProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return User.internal_static_UserInfoProto_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return User.internal_static_UserInfoProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UserInfoProto.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                name_ = "";

                age_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return User.internal_static_UserInfoProto_descriptor;
            }

            public UserInfoProto getDefaultInstanceForType() {
                return UserInfoProto.getDefaultInstance();
            }

            public UserInfoProto build() {
                UserInfoProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public UserInfoProto buildPartial() {
                UserInfoProto result = new UserInfoProto(this);
                result.id_ = id_;
                result.name_ = name_;
                result.age_ = age_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof UserInfoProto) {
                    return mergeFrom((UserInfoProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(UserInfoProto other) {
                if (other == UserInfoProto.getDefaultInstance()) return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                UserInfoProto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (UserInfoProto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 指定字段类型为 string，标识号为 1
             * </pre>
             *
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>uint32 age = 3;</code>
             */
            public int getAge() {
                return age_;
            }

            /**
             * <code>uint32 age = 3;</code>
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 age = 3;</code>
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:UserInfoProto)
        }

    }

    /**
     * Protobuf type {@code UserDetailProto}
     */
    public static final class UserDetailProto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:UserDetailProto)
            UserDetailProtoOrBuilder {
        public static final int USERINFO_FIELD_NUMBER = 1;
        public static final int PASS_WORD_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:UserDetailProto)
        private static final UserDetailProto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<UserDetailProto>
                PARSER = new com.google.protobuf.AbstractParser<UserDetailProto>() {
            public UserDetailProto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UserDetailProto(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new UserDetailProto();
        }

        private UserInfoProto userInfo_;
        private volatile Object passWord_;
        private byte memoizedIsInitialized = -1;

        // Use UserDetailProto.newBuilder() to construct.
        private UserDetailProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private UserDetailProto() {
            passWord_ = "";
        }

        private UserDetailProto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            UserInfoProto.Builder subBuilder = null;
                            if (userInfo_ != null) {
                                subBuilder = userInfo_.toBuilder();
                            }
                            userInfo_ = input.readMessage(UserInfoProto.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(userInfo_);
                                userInfo_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            passWord_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return User.internal_static_UserDetailProto_descriptor;
        }

        public static UserDetailProto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserDetailProto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserDetailProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserDetailProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserDetailProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UserDetailProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UserDetailProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserDetailProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserDetailProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static UserDetailProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static UserDetailProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UserDetailProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(UserDetailProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static UserDetailProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<UserDetailProto> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return User.internal_static_UserDetailProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UserDetailProto.class, Builder.class);
        }

        /**
         * <code>.UserInfoProto userInfo = 1;</code>
         */
        public boolean hasUserInfo() {
            return userInfo_ != null;
        }

        /**
         * <code>.UserInfoProto userInfo = 1;</code>
         */
        public UserInfoProto getUserInfo() {
            return userInfo_ == null ? UserInfoProto.getDefaultInstance() : userInfo_;
        }

        /**
         * <code>.UserInfoProto userInfo = 1;</code>
         */
        public UserInfoProtoOrBuilder getUserInfoOrBuilder() {
            return getUserInfo();
        }

        /**
         * <code>string pass_word = 2;</code>
         */
        public String getPassWord() {
            Object ref = passWord_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                passWord_ = s;
                return s;
            }
        }

        /**
         * <code>string pass_word = 2;</code>
         */
        public com.google.protobuf.ByteString
        getPassWordBytes() {
            Object ref = passWord_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                passWord_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (userInfo_ != null) {
                output.writeMessage(1, getUserInfo());
            }
            if (!getPassWordBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, passWord_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (userInfo_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getUserInfo());
            }
            if (!getPassWordBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, passWord_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof UserDetailProto)) {
                return super.equals(obj);
            }
            UserDetailProto other = (UserDetailProto) obj;

            boolean result = true;
            result = result && (hasUserInfo() == other.hasUserInfo());
            if (hasUserInfo()) {
                result = result && getUserInfo()
                        .equals(other.getUserInfo());
            }
            result = result && getPassWord()
                    .equals(other.getPassWord());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUserInfo()) {
                hash = (37 * hash) + USERINFO_FIELD_NUMBER;
                hash = (53 * hash) + getUserInfo().hashCode();
            }
            hash = (37 * hash) + PASS_WORD_FIELD_NUMBER;
            hash = (53 * hash) + getPassWord().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<UserDetailProto> getParserForType() {
            return PARSER;
        }

        public UserDetailProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code UserDetailProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:UserDetailProto)
                UserDetailProtoOrBuilder {
            private UserInfoProto userInfo_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    UserInfoProto, UserInfoProto.Builder, UserInfoProtoOrBuilder> userInfoBuilder_;
            private Object passWord_ = "";

            // Construct using com.jsj.rpc.proto.User.UserDetailProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return User.internal_static_UserDetailProto_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return User.internal_static_UserDetailProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UserDetailProto.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (userInfoBuilder_ == null) {
                    userInfo_ = null;
                } else {
                    userInfo_ = null;
                    userInfoBuilder_ = null;
                }
                passWord_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return User.internal_static_UserDetailProto_descriptor;
            }

            public UserDetailProto getDefaultInstanceForType() {
                return UserDetailProto.getDefaultInstance();
            }

            public UserDetailProto build() {
                UserDetailProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public UserDetailProto buildPartial() {
                UserDetailProto result = new UserDetailProto(this);
                if (userInfoBuilder_ == null) {
                    result.userInfo_ = userInfo_;
                } else {
                    result.userInfo_ = userInfoBuilder_.build();
                }
                result.passWord_ = passWord_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof UserDetailProto) {
                    return mergeFrom((UserDetailProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(UserDetailProto other) {
                if (other == UserDetailProto.getDefaultInstance()) return this;
                if (other.hasUserInfo()) {
                    mergeUserInfo(other.getUserInfo());
                }
                if (!other.getPassWord().isEmpty()) {
                    passWord_ = other.passWord_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                UserDetailProto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (UserDetailProto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public boolean hasUserInfo() {
                return userInfoBuilder_ != null || userInfo_ != null;
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public UserInfoProto getUserInfo() {
                if (userInfoBuilder_ == null) {
                    return userInfo_ == null ? UserInfoProto.getDefaultInstance() : userInfo_;
                } else {
                    return userInfoBuilder_.getMessage();
                }
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public Builder setUserInfo(UserInfoProto value) {
                if (userInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    userInfo_ = value;
                    onChanged();
                } else {
                    userInfoBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public Builder setUserInfo(
                    UserInfoProto.Builder builderForValue) {
                if (userInfoBuilder_ == null) {
                    userInfo_ = builderForValue.build();
                    onChanged();
                } else {
                    userInfoBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public Builder mergeUserInfo(UserInfoProto value) {
                if (userInfoBuilder_ == null) {
                    if (userInfo_ != null) {
                        userInfo_ =
                                UserInfoProto.newBuilder(userInfo_).mergeFrom(value).buildPartial();
                    } else {
                        userInfo_ = value;
                    }
                    onChanged();
                } else {
                    userInfoBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public Builder clearUserInfo() {
                if (userInfoBuilder_ == null) {
                    userInfo_ = null;
                    onChanged();
                } else {
                    userInfo_ = null;
                    userInfoBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public UserInfoProto.Builder getUserInfoBuilder() {

                onChanged();
                return getUserInfoFieldBuilder().getBuilder();
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            public UserInfoProtoOrBuilder getUserInfoOrBuilder() {
                if (userInfoBuilder_ != null) {
                    return userInfoBuilder_.getMessageOrBuilder();
                } else {
                    return userInfo_ == null ?
                            UserInfoProto.getDefaultInstance() : userInfo_;
                }
            }

            /**
             * <code>.UserInfoProto userInfo = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    UserInfoProto, UserInfoProto.Builder, UserInfoProtoOrBuilder>
            getUserInfoFieldBuilder() {
                if (userInfoBuilder_ == null) {
                    userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            UserInfoProto, UserInfoProto.Builder, UserInfoProtoOrBuilder>(
                            getUserInfo(),
                            getParentForChildren(),
                            isClean());
                    userInfo_ = null;
                }
                return userInfoBuilder_;
            }

            /**
             * <code>string pass_word = 2;</code>
             */
            public String getPassWord() {
                Object ref = passWord_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    passWord_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string pass_word = 2;</code>
             */
            public Builder setPassWord(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                passWord_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string pass_word = 2;</code>
             */
            public com.google.protobuf.ByteString
            getPassWordBytes() {
                Object ref = passWord_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    passWord_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string pass_word = 2;</code>
             */
            public Builder setPassWordBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                passWord_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string pass_word = 2;</code>
             */
            public Builder clearPassWord() {

                passWord_ = getDefaultInstance().getPassWord();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:UserDetailProto)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
